name = "example-durable-object-v2"
main = "src/index.ts"
compatibility_date = "2022-11-15"

account_id = "<your account ID>"
workers_dev = true

[durable_objects]
bindings = [{name = "PERSON", class_name = "Person"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Person"]